const Faker = [
    {
      "source": "SWOT",
      "what": "Revisão da Política",
      "why": "Inclusão ISO 45001",
      "where": "SGI",
      "when": "out.-21",
      "who": "Lais",
      "validation": "Alessandra / Direção",
      "how": "Analisar necessidade de inclusão dos itens de Saúde e Segurança que estão de forma abrangente (verificar necessidade)",
      "how_much": "Custo com Certificação",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "SWOT",
      "what": "Revisar Objetivos do SGI",
      "why": "Inclusão ISO 45001",
      "where": "SGI",
      "when": "out.-21",
      "who": "Lais",
      "validation": "Alessandra / Direção",
      "how": "Atribuir requisitos de Saúde e Segurança",
      "how_much": "Custo com Certificação",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "O/MEL",
      "what": "Revisão do Método de Construção da Análise Crítica (apresentação de resultados semenstre)",
      "why": "A reunião da Análise Crítica estava sendo realizada via power point de forma resumida",
      "where": "SGI",
      "when": "ago.-21",
      "who": "Lais",
      "validation": "Alessandra/Direção",
      "how": "Criar uma ata de Análise Crítica em Word, descrevendo de forma geral os itens aplicados as normas certificadas",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "O/MEL",
      "what": "Revisão do Método de Construção da Análise Crítica",
      "why": "As informações de Entrada e saída não estavam sendo monitoradas",
      "where": "SGI",
      "when": "ago.-21",
      "who": "Lais",
      "validation": "Alessandra/Direção",
      "how": "Incluir nessa ata de análise crítica ações de Entrada da ata discutida anteriormente (através de uma tabela)",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "SWOT",
      "what": "Realizar inclusão dos requistos relacionados a 45001 na reunião de análise crítica",
      "why": "Inclusão ISO 45001",
      "where": "SGI",
      "when": "set.-21",
      "who": "Lais",
      "validation": "Alessandra/Direção",
      "how": "Incluir nessa ata de análise crítica ações de Saída discutidas em reunião (através de uma tabela)",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "AMBILEGIS",
      "what": "Realizar Laudo Ergônomico por área",
      "why": "Inclusão ISO 45001",
      "where": "SGI",
      "when": "out.-21",
      "who": "Prestador de Serviço",
      "validation": "Lais/Rafael",
      "how": "Analisar custos por departamento para iniciar programações",
      "how_much": "PC12635",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "AMBILEGIS",
      "what": "Documentação da LCTAT - SESI",
      "why": "Inclusão ISO 45001",
      "where": "SGI",
      "when": "out.-21",
      "who": "SESI",
      "validation": "Lais/Rafael",
      "how": "Conforme acordado com o Prestador de Serviço",
      "how_much": "PC12868",
      "status": "Em revisão",
      "extended_to": "mar.-22"
    },
    {
      "source": "MUDANÇA",
      "what": "Implantação do Sistema de Requisitos Legais - Ambilegis",
      "why": "Imputar registros e responsáveis (45001 e 14001)",
      "where": "SGI",
      "when": "dez.-21",
      "who": "Lais / Alessandra",
      "validation": "Lais / Alessandra",
      "how": "Atualizar os responsáveis e registros para cada requisito legal aplicável ao escopo",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "RNC",
      "what": "Elaborar plano de comunicação para itens pertinentes do SGI",
      "why": "No requisito 7.4 Comunicação a norma ressalta no item a) que a empresa deve determinar \"quando\" comunicar",
      "where": "SGI",
      "when": "jan.-22",
      "who": "SGI / RH",
      "validation": "Alessandra/Laís",
      "how": "Realizar em conjunto com o RH um plano de comunicados.",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Objetivos e Planejamento",
      "what": "Cronograma Anual de Treinamentos Previstos x Realizados",
      "why": "Com base nos requisitos 7.2 conforme determinação da competência necessária, não foi observado como monitoramos as execuções dos treinamentos realizados",
      "where": "SGI/RH",
      "when": "nov.-21",
      "who": "SGI / RH",
      "validation": "Alessandra",
      "how": "Analisar a Criação de um Cronograma Anual com os treinamentos previstos x realizados e sinalizar os resultados das avaliações da Eficácia de todos os treinamentos realizados conforme aplicáveis.",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "ISO9001",
      "what": "Realizar auditoria interna - agosto/21",
      "why": "Cumprir cronograma anual - conforme procedimento de auditoria",
      "where": "Bree",
      "when": "ago.-21",
      "who": "Consultoria Externa",
      "validation": "Alessandra/Lais",
      "how": "Contratação de empresa terceirizada para auditar as áreas, incluindo dados da norma ISO 45001",
      "how_much": "R$ 2.400,00",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "O/MEL",
      "what": "Realizar Instrução de Trabalho visual nas áreas operacionais",
      "why": "Melhorar a comunicação dos procedimentos de trabalho para as equipes operacionais",
      "where": "Fábrica",
      "when": "ago.-21",
      "who": "Lais",
      "validation": "Alessandra / Gilvani",
      "how": "a) Adaptar Instruções de Trabalho que facilitem a comunicação das rotinas operacionais; b) As instruções devem ficar localizadas próximos aos colaboradores.",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "GESTÃO SSO",
      "what": "Através da prática de DDS melhorar a comunicação sobre os Perigos e Riscos Ocupacionais nas áreas reforçando o controle LPRO",
      "why": "Falha na comunicação dos Perigos e Riscos Ocupacionais, reforçar a prática de controle para os envolvidos.",
      "where": "Adm e Operacional",
      "when": "ago.-21",
      "who": "Lais/Rafael",
      "validation": "Alessandra",
      "how": "Semanalmente reforçar nas práticas de DDS o conteúdo dos principais perigos e riscos levantados no LPRO. \nUtilizar as práticas de 5S como apoio na disseminação do conteúdo de Riscos Ocupacionais",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "AMBILEGIS",
      "what": "Orçamento Fornecedores para a realização de NR 12",
      "why": "Garantir controle de Segurança de Máquinas e Equipamentos",
      "where": "Fábrica",
      "when": "ago.-21",
      "who": "Contratação Terceiro",
      "validation": "Alessandra/Lais",
      "how": "Buscar profissionais no mercado que realizem a prestação de serviços - Laudo NR 12",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Parte Interessada - Fornecedor",
      "what": "Recomendações em Laudo Técnico nº 073/21 - Bill Maker Qualidade Ltda",
      "why": "Conforme exigência da NR 13 - providenciar cercado de Proteção para a central conforme padrão AIR PRODUCTS e, \nPonto de água com mangueira para descongelamento das válvulas.",
      "where": "Área externa Fábrica",
      "when": "dez.-22",
      "who": "Contratação Terceiro",
      "validation": "Alessandra/Laís",
      "how": "Através de contratação de empresa especializada seguindo as exigências da NR13",
      "how_much": "Em orçamento",
      "status": "Planejado",
      "extended_to": "marco/22"
    },
    {
      "source": "GESTÃO SGI",
      "what": "Preparar reunião de análise crítica",
      "why": "Critério das normas 9001 e 14001",
      "where": "Diretoria",
      "when": "08/12/2021",
      "who": "Alessandra",
      "validation": "Antonio",
      "how": "Preparar as entradas de reunião da anáise crítica em formato de ata",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "GESTÃO SGI",
      "what": "Orçamento de fornecedores para a realização de NR10",
      "why": "Garantir a segurança em instalações e servicos com eletricidade",
      "where": "Fábrica",
      "when": "dez.-21",
      "who": "Lais/Rafael/Alessandra",
      "validation": "Alessandra/Lais",
      "how": "Buscar profissionais no mercado que realizem a prestação de serviços - Laudo NR 10",
      "how_much": "Em análise",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "SWOT",
      "what": "Aquisição APR NR 12",
      "why": "Atnedimento a NR12",
      "where": "Fábrica",
      "when": "out.-21",
      "who": "Contratação Terceiro",
      "validation": "Alessandra/Laís",
      "how": "Contratar profissional para elaborar a apreciação de risco de todas as máquinas da fábrica",
      "how_much": "PC12869",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "SWOT",
      "what": "Implantação do programa de proteção auditiva",
      "why": "Atendimento a requisito legal",
      "where": "Bree",
      "when": "jan.-22",
      "who": "SGI/RH",
      "validation": "SGI/RH",
      "how": "Implantação do programa de proteção auditiva e ecoleta de assinaturas",
      "how_much": "N/A",
      "status": "Em andamento",
      "extended_to": "abr.-22"
    },
    {
      "source": "SWOT",
      "what": "Implantação ordem de serviço (NR1)",
      "why": "Atendimento a NR1",
      "where": "Bree",
      "when": "dez.-21",
      "who": "SGI/RH",
      "validation": "SGI/RH",
      "how": "Implantação da ordem de serviço e ecoleta de assinaturas",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "SWOT",
      "what": "Adequação NR 12",
      "why": "A partir da apreciação de risco, adequar a máqina para atendimento da NR12",
      "where": "Fábrica",
      "when": "dez.-22",
      "who": "Contratação Terceiro",
      "validation": "Alessandra/Laís",
      "how": "Comprar materiais necessários e realizar a adaptação necessária",
      "how_much": "Orçamento 2022",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Objetivos e Planejamento",
      "what": "Implantar o Laudo insalubridade e periculosidade",
      "why": "Garantir e cumprir o requisito de saúde e segurança do trabalho",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Alessandra/Lais/Rafael",
      "validation": "Alessandra/Lais",
      "how": "Acompanhar empresa responsável para realizar o laudo técnico",
      "how_much": "PC12868",
      "status": "Em revisão",
      "extended_to": "mar.-22"
    },
    {
      "source": "Gestão SGA",
      "what": "Desenvolver fornecedor para destinação de Percloroetileno",
      "why": "Cumprir requisitos de destinação de resíduo",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Análise de documental dos fornecedores aptos a essa destinação",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Realizar Inventário de resíduo nos sistemas (SGA, SINIR e RAPP)",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "abr.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Levantamento das informações referentes ao ano 2020 e registro nos dados do IAT/SINIR/RAPP",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Solicitar Autorização ambiental para o IAT",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "abr.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Solicitado no sistema SGA",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Realizar auditoria em fornecedor de resíduo (Filtroil)",
      "why": "Garantir que o fornecedor cumpre com os requisitos ambientais",
      "where": "Bree",
      "when": "abr.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Realizar auditoria interna no fornecedor",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Elaborador indicadores de gestão ambientais",
      "why": "Garantir atendimento a norma ISO 14001",
      "where": "Bree",
      "when": "abr.-21",
      "who": "Alessandra/Halisson",
      "validation": "Antonio",
      "how": "Início da pesagem dos resíduos da bobinagem",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Realizar análise de impacto de ruído (Tec ambiental)",
      "why": "Garantir atendimento ao requisito da licença de operação ambiental",
      "where": "Bree",
      "when": "mai.-21",
      "who": "Alessandra",
      "validation": "Halisson",
      "how": "Contratação de empresa terceirizada para realizar o serviço",
      "how_much": "R$ 1.500,00",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Solicitar SERFLOR - IAT",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "jun.-21",
      "who": "Halisson",
      "validation": "Halisson",
      "how": "Solicitar SERFLOR no sistema do IAT",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Implantar Ficha de Emergência e Elaborar FDSR",
      "why": "Cumprir requisitos legais ambientais (PGRS)",
      "where": "Bree",
      "when": "ago.-21",
      "who": "Alessandra/Halisson",
      "validation": "Alessandra/Halisson",
      "how": "Elaborar a ficha de de emergência e ficha de dados de segurança de resíduo",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Atualização CTF",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "set.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Atualizar CTF no sistema do IBAMA",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Desenvolver fornecedor para Bauxita",
      "why": "Cumprir requisitos legais ambientais (PGRS)",
      "where": "Bree",
      "when": "jun.-21",
      "who": "Alessandra/Halisson",
      "validation": "Halisson",
      "how": "Avaliar resíduo e definir fornecedor apto a receber a bauxita",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Implantação LAIA no sistema CAP (ambilegis)",
      "why": "Melhorar controle de aspectos e impactos por sistema vinculado com a legislação",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Alessandra/Lais",
      "validation": "Alessandra/Lais",
      "how": "Revisar planilha de aspectos e impactos e enviar para a ambilegis imputar no sistema",
      "how_much": "N/A",
      "status": "Cancelado",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Renovação licença Ambiental",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Halisson",
      "validation": "Alessandra/Lais",
      "how": "Solicitar renovação no sistema do IAT",
      "how_much": "N/A",
      "status": "Em andamento",
      "extended_to": "abr.-22"
    },
    {
      "source": "Gestão SGA",
      "what": "Atualização PGRS",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "set.-21",
      "who": "Halisson",
      "validation": "Alessandra/Lais",
      "how": "Levantar dados de resíduos gerado para e revisar plano de gerenciamento de resíduos",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Alteração do CNPJ da licença de operação para a filial 02",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "ago.-21",
      "who": "Halisson",
      "validation": "Halisson",
      "how": "Solicitar alteração no sistema do IAT",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Definir método de destinação de pilhas e baterias",
      "why": "Cumprir requisitos legais ambientais",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Halisson",
      "validation": "Halisson",
      "how": "Devido ao baixo volume, encontrar ponto de coleta de logística reversa na região de quatro barras",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGI",
      "what": "Realizar inspeção no vaso de pressão (VP 170062 / VP1231 / VP 3293)",
      "why": "Cumprir requisito de saúde e segurança (NR13)",
      "where": "Impregnação",
      "when": "set.-21",
      "who": "Alessandra/Lais",
      "validation": "Alessandra/Lais",
      "how": "Realizar inspeção nos 3 vasos de pressão da autoclave",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Laudo de Inspeção dos Vasos - NR13",
      "what": "Incluir válvula de segurança dos vasos de pressão no controle geral de calibração",
      "why": "Cumprir requisito de saúde e segurança (NR13)",
      "where": "SGI",
      "when": "jan.-22",
      "who": "Laís",
      "validation": "Alessandra",
      "how": "Incluir válvula no controle e monitoramento do SGI",
      "how_much": "N/A",
      "status": "Planejado",
      "extended_to": "mar.-22"
    },
    {
      "source": "PGRS",
      "what": "Renovação da carta de anuência para limpeza da fossa séptica (SANEPAR)",
      "why": "Cumprir requisito de meio ambiente",
      "where": "Bree",
      "when": "set.-21",
      "who": "Halisson",
      "validation": "Alessandra/Lais",
      "how": "Solicitar para a Sanepar renovação da carta de anuência para destinação de resíduo da fossa séptica",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGA",
      "what": "Coletar resíduos biológicos da fossa sépitica",
      "why": "Cumprir requisito de meio ambiente",
      "where": "Bree",
      "when": "set.-21",
      "who": "Halisson",
      "validation": "Alessandra/Lais",
      "how": "Agendar coleta para retirada e destinação final do resíduo",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGI",
      "what": "Implementar qualificação do processo de solda do reator e qualificar novos soldadores",
      "why": "Garantia do processo de solda para produtos",
      "where": "Reator",
      "when": "mar.-22",
      "who": "Sylvio",
      "validation": "Alessandra/Lais",
      "how": "Agendar processo de qualificação com prestador de servico qualificado",
      "how_much": "N/A",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Gestão SGI",
      "what": "Realizar a SIPAT",
      "why": "Cumprir requisitos de saúde e segurança",
      "where": "Bree",
      "when": "set.-21",
      "who": "Jenifer/Rafael",
      "validation": "Alessandra/Lais",
      "how": "Planejar evento da SIPAT (13 a 17 de setembro)",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Gestão SGI",
      "what": "Realizar ensaio de luva de alta tensão",
      "why": "Cumprir requisito de NR10",
      "where": "Bree",
      "when": "nov.-21",
      "who": "Alessandra/Lais",
      "validation": "Alessandra/Lais",
      "how": "Enviar as luvas para ensaio",
      "how_much": "Aguardando PC",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Gestão SGI",
      "what": "Renovar acesso a normas brasileiras - TARGET",
      "why": "Garantir acesso as normas de qualidade em sua última versão",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Alessandra/Lais",
      "validation": "Alessandra/Lais",
      "how": "Renovar assinatura da Target normas",
      "how_much": "Aguardando PC",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Melhoria",
      "what": "Oportunidade de melhoria - Verifcar possibilidade de ordem de produção para a cordoalha",
      "why": "Para reduzir desperdícios de cordolahas",
      "where": "Montagem dos capacitores",
      "when": "dez.-22",
      "who": "Alessandra",
      "validation": "PCP/Eng",
      "how": "Analisar posto de trabalho para identificar a redução de resíduo pela implantação de ordem de serviço para cordoalha",
      "how_much": "N/A",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Auditoria Interna",
      "what": "Revisão de procedimentos",
      "why": "Atualização do procedimentos para modelo de instrução de trabalho e modelo bree",
      "where": "Bree",
      "when": "Jan/22 –",
      "who": "Laís",
      "validation": "Alessandra",
      "how": "Migrar todos procedimentos Bree para novo modelo",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Adequação a ISO14067 - Pegada de Carbono",
      "why": "Requisito Cliente",
      "where": "Bree - Cliente",
      "when": "jul.-22",
      "who": "SGI",
      "validation": "Comercial",
      "how": "Buscar órgão certificado apto a auditar a iso 14067 acreditado",
      "how_much": "Contrato cliente",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Adequação LGPD",
      "why": "Requisitos legais",
      "where": "Bree",
      "when": "dez.-22",
      "who": "Juliana/TI/jurídico",
      "validation": "Juliana/TI/jurídico",
      "how": "Analisar impactos da LGPD na Bree e adequar",
      "how_much": "N/A",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Realizar melhorias no TOTVS para aderência aos processos",
      "why": "Melhorias em TI",
      "where": "Bree",
      "when": "dez.-22",
      "who": "Contratação Terceiro",
      "validation": "Juliana/TI",
      "how": "Corrigir e realizar melhorias no TOTVS",
      "how_much": "Orçamento 21/22",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Inclusão da Controladoria no MACROFLUXO",
      "why": "Incluir nova área nos processos do SGI",
      "where": "SGI",
      "when": "jul.-21",
      "who": "Liane/Juliana",
      "validation": "Laís",
      "how": "Atualização do macrofluxo e criação de procedimentos da área",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Adequar fluxo de entrada no Laboratório (Planejamento de mudanças - item b. 2021)",
      "why": "Inclusão de tag para entrada de funcionários e porta de acesso.",
      "where": "SGI/Manutenção",
      "when": "dez.-21",
      "who": "Gilvani",
      "validation": "Alessandra/Laís",
      "how": "Contratar prestador de serviço para executar",
      "how_much": "PC13503",
      "status": "Em andamento",
      "extended_to": "abr.-22"
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Implantar ISO45001 - (Escopo/Política/Objetivos entre outros)",
      "why": "Ampliar escopo de certifificação",
      "where": "SGI",
      "when": "jan.-22",
      "who": "Laís",
      "validation": "Laís/Alessandra",
      "how": "Realizar auditoria externa",
      "how_much": "PC13703",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Cadastrar escopo dos ensaios realizados no Laboratório para buscar certificação ISO17025",
      "why": "Capacitação do Laboratório mediante aos ensaios",
      "where": "Laboratório",
      "when": "dez.-22",
      "who": "Lais",
      "validation": "Laís",
      "how": "a) Realização de input de informações na página orquestra no site do INMETRO.",
      "how_much": "Em análise",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Revisar sistemática de acompanhamento de RNC",
      "why": "Revisar sistemática de forma a tornar a facilitar a gestão",
      "where": "SGI",
      "when": "fev.-21",
      "who": "Alessandra",
      "validation": "Laís",
      "how": "Criar formulário em excel, que facilita a abertura e gestão das NC",
      "how_much": "N/A",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Realizar, adequar sistemática de Fornecedor",
      "why": "Revisas sistemática de avaliação de fornecedor (SGQ)",
      "where": "SGI",
      "when": "dez.-21",
      "who": "Alessandra",
      "validation": "Laís",
      "how": "Adequar sistemática de avaliação",
      "how_much": "N/A",
      "status": "Em andamento",
      "extended_to": "abr.-22"
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Implantar Programas de Saúde e Segurança Ocupacional",
      "why": "Implantar programas relacioandos a requisitos legais",
      "where": "SGI",
      "when": "dez.-21",
      "who": "Laís",
      "validation": "Alessandra",
      "how": "Contratar prestadores de serviço para implantação de programas de SSO como LTCAT, LIP",
      "how_much": "PC12868",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Reduzir falhas em capacitores",
      "why": "Analisar processo de capacitor para encontrar falhas no processo",
      "where": "Eng MT",
      "when": "jan.-21",
      "who": "Hugo",
      "validation": "Eng MT",
      "how": "Realizar avaliação de processo",
      "how_much": "N/A",
      "status": "Em andamento",
      "extended_to": "jun.-22"
    },
    {
      "source": "Análise Crítica 10/08/21",
      "what": "Implantar avaliação de performance e programa de remuneração variável.",
      "why": "Implantar programa",
      "where": "RH",
      "when": "dez.-21",
      "who": "Pedro",
      "validation": "Diretoria",
      "how": "Implantar programa",
      "how_much": "Orçamento 21",
      "status": "Em andamento",
      "extended_to": "mar.-22"
    },
    {
      "source": "SWOT",
      "what": "Certitificação Produto TCA - Certificação 3ª Parte",
      "why": "Atendimento Norma ISO17065",
      "where": "Eng MT",
      "when": "dez.-21",
      "who": "Alessandra/joão",
      "validation": "Contratos",
      "how": "Contratar órgão certificado apto e realizar ensaio",
      "how_much": "Contrato cliente",
      "status": "Em andamento",
      "extended_to": "jun.-22"
    },
    {
      "source": "Controle de Mudanças",
      "what": "Inclusão de um novo produto no escopo de certificação (SAV/CAT 2021 1A)",
      "why": "Incluir novo produto fabricadon pela Bree no escopo",
      "where": "Bree",
      "when": "jan.-22",
      "who": "Fabrício/Edson",
      "validation": "Alessandra/Laís",
      "how": "Solicitar alteração do escopo para TECPAR e incluir processos das chaves na Bree",
      "how_much": "PC13703",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Substituição de Equipe de Manutenção",
      "why": "Gestão de pessoas",
      "where": "Manutenção",
      "when": "dez.-21",
      "who": "Gilvani",
      "validation": "Gilvani",
      "how": "Buscar novo profissional focado em manutenção preventiva e melhorias",
      "how_much": "Orçamento 21",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Contratação de mais uma pessoa na manutenção focada em ações de melhorias de máquinas",
      "why": "Melhor processos",
      "where": "Melhorias",
      "when": "nov.-21",
      "who": "Alessandra",
      "validation": "Gilvani",
      "how": "Buscar novo profissional focado em manutenção preventiva e melhorias",
      "how_much": "Orçamento 21",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Homologação de Fornecedor de Gerenciamento de Resíduos para óleo lubrificante (LWART e FiltroVille) Necessário solicitar Autorização com o IAP para validar formalização com o fornecedor. FiltroVille quem irá coletar o percloroetileno.",
      "why": "Desenvolver fornecedor para respiduos",
      "where": "SGA",
      "when": "dez.-21",
      "who": "Alessandra/Laís",
      "validation": "Halisson",
      "how": "Desenvolver fornecedor para destinar percloroetileno, com auotorização ambiental",
      "how_much": "Taxa IAT",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Implantar cronograma de adequação das máquinas",
      "why": "Elaborar cronograma de implantação",
      "where": "Fábrica",
      "when": "dez.-22",
      "who": "Alessandra/Laís",
      "validation": "Eng. Robson",
      "how": "Adequar máquina a máquina",
      "how_much": "Orçamento 22",
      "status": "Planejado",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Laudo LTCAT",
      "why": "Aquisição de LTCAT",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Alessandra/Laís/Pedro",
      "validation": "Alessandra/Laís/Pedro",
      "how": "Aquisição de laudo quntitativo",
      "how_much": "PC12868",
      "status": "Em revisão",
      "extended_to": "mar.-22"
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Treinamento dos Líderes da Produção e Matriz de Polivalência.",
      "why": "Realizar treinamento",
      "where": "Fábrica",
      "when": "dez.-21",
      "who": "RH/SGI",
      "validation": "Gilvani",
      "how": "Realizar treinamento de lidernça e conscientização de treinamento para elaboração de matriz polivalência",
      "how_much": "NA",
      "status": "Planejado",
      "extended_to": "jun.-22"
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Projeto de 5S para início de Janeiro.",
      "why": "Definir sistemática de auditoria 5S",
      "where": "Bree",
      "when": "jan.-22",
      "who": "SGI",
      "validation": "Diretoria",
      "how": "Elaborar sistemática para auditoria mensal de 5S em todas áreas da Bree",
      "how_much": "NA",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Sinalização das Máquinas e Equipamentos.",
      "why": "Aquisição de adesivos de sinalização para riscos relacionados a máquinas",
      "where": "Fábrica",
      "when": "dez.-21",
      "who": "SGI",
      "validation": "Engº Robson",
      "how": "Aquisição de adesivos colantes para identificação de riscos relacionados a máquinas",
      "how_much": "Orçamento 21",
      "status": "Planejado",
      "extended_to": "mar.-22"
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Sinalização da Área de Não Conformidade.",
      "why": "Definir área não conforme",
      "where": "Fábrica",
      "when": "dez.-21",
      "who": "SGI",
      "validation": "SGI",
      "how": "Sinalizar com vermelho as áreas não conformes",
      "how_much": "NA",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Sinalização das áreas com as pastas para consulta de procedimentos e registros do SST.",
      "why": "Padronização de pastas de procedimentos nas áreas produtivas",
      "where": "Fábrica",
      "when": "dez.-21",
      "who": "SGI",
      "validation": "SGI",
      "how": "Aquisição de pastas para sinalização de procedimentos nas áreas produtivas",
      "how_much": "Orçamento 21",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Diagnóstico de NR 10 – Dez/21.",
      "why": "Elaborar internamente diagnóticos de NR10 e definir plano de ação",
      "where": "Bree",
      "when": "dez.-21",
      "who": "SGI",
      "validation": "SGI",
      "how": "Elaborar diagnóstico de NR10 e plano de ação",
      "how_much": "NA",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Elaboração do Projeto NR35.",
      "why": "Elaborar projeto de linha vida para áreas com trabalho em altura",
      "where": "Bree",
      "when": "nov.-21",
      "who": "Prestador de Serviço",
      "validation": "SGI",
      "how": "Aquisição de projeto para implantar linha de vida",
      "how_much": "PC12869",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Realização da AET – Adequar novos programas de gestão de SSO 2022.",
      "why": "Planejar novos programas de SSO",
      "where": "Bree",
      "when": "dez.-22",
      "who": "Prestador de Serviço",
      "validation": "SGI",
      "how": "Planejamento de novos programas de SSO para 2022",
      "how_much": "Orçamento 22",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Revisão de Procedimentos – alteração de códigos, metodologia de layout",
      "why": "Revisão de procedimentos para novo modelo Bree e instrução de trabalho",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Bree",
      "validation": "SGI",
      "how": "Atualizar todos os procedimentos",
      "how_much": "NA",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Renovação da licença ambiental",
      "why": "preparar documentação para renovação da licença ambiental",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Prestador de Serviço",
      "validation": "SGI",
      "how": "Preparar documentação para renovação da licença",
      "how_much": "Taxa IAT",
      "status": "Em andamento",
      "extended_to": ""
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Revisar TI – Mapear Procedimentos para obter rastreabilidade",
      "why": "Elaborar procedimentos da área de TI (após tercerizaçaõ)",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Prestador de Serviço",
      "validation": "SGI",
      "how": "Elaborar procedimento",
      "how_much": "NA",
      "status": "Planejado",
      "extended_to": "abr.-22"
    },
    {
      "source": "Análise crítica extraordinária 18/11/21",
      "what": "Contratação Advogado (a) para tratar ações direcionadas a parte trabalhista e contratadas e Regularização documental (ASO)",
      "why": "Contratação de advogada trabalhista para auxiliar na atualização do contrato de terceiros, de forma atender os requisitos da iso45001",
      "where": "Bree",
      "when": "Jan/22 – Junho/22",
      "who": "Prestador de Serviço",
      "validation": "SGI/RH/JURídico",
      "how": "Analisar com auxílio de advogada trabalhista, a alteração de contratos de PJ para atender os requisitos da 45001",
      "how_much": "Orçamento 22",
      "status": "Planejado",
      "extended_to": "jun.-22"
    },
    {
      "source": "Gestão SGQ",
      "what": "Atualizar AROP",
      "why": "Atualizar AROP das áreas",
      "where": "Bree",
      "when": "fev.-22",
      "who": "Bree",
      "validation": "SGI",
      "how": "Atualizar AROP",
      "how_much": "NA",
      "status": "Planejado",
      "extended_to": "abr.-22"
    },
    {
      "source": "Gestão SGQ",
      "what": "Realizar treinamento dos procedimentos operacionais",
      "why": "Finalizar treinamentos operacionais dos procedimentos atualizados",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Bree",
      "validation": "SGI",
      "how": "Lista de treinamento",
      "how_much": "NA",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "SSO",
      "what": "Detetização de copa",
      "why": "Evitar proliferação de pragas",
      "where": "Bree",
      "when": "jan.-22",
      "who": "Prestador de Serviço",
      "validation": "SGI",
      "how": "Contratação de empresa para realização de servhiço",
      "how_much": "NA",
      "status": "Planejado",
      "extended_to": "mar.-22"
    },
    {
      "source": "SSO",
      "what": "Substituição de filtros de água",
      "why": "Garantir a potabilidade da água",
      "where": "Bree",
      "when": "dez.-21",
      "who": "Bree",
      "validation": "SGI",
      "how": "Compra do filtro",
      "how_much": "NA",
      "status": "Concluído",
      "extended_to": ""
    },
    {
      "source": "Simulado de emergência",
      "what": "Realizar simulado de vazamento de produto químico",
      "why": "Para garantir que em caso de emergência ambiental, a brigada terá condições de conter",
      "where": "Bree",
      "when": "fev.-22",
      "who": "Rafael",
      "validation": "SGI",
      "how": "Planejar e realizar simulado de derramamento de produto químico",
      "how_much": "NA",
      "status": "Planejado",
      "extended_to": "mar.-22"
    },
    {
      "source": "Simulado de emergência 04/2021",
      "what": "Compra de chave de emergência para o almoxarifado",
      "why": "Garantir rota de fuga dos colaboradores",
      "where": "Bree",
      "when": "fev.-22",
      "who": "Alessandra",
      "validation": "SGI",
      "how": "Garantir rota de fuga em caso de emergência",
      "how_much": "NA",
      "status": "Concluído",
      "extended_to": ""
    }
  ]

export default Faker;  